import { COMMON_COMPONENT_TEXT, COMMON_TEXT } from './common';
import {
  SIGNUP_TEXT,
  SELECT_TEXT,
  SET_PROFILE_TEXT,
  SIGNUP_COMPLETE_TEXT,
} from './beforeLogin';
import { ACCOUNT_TEXT } from './account';

export const TEXT = {
  COMMON: { ...COMMON_TEXT },
  COMMON_COMPONENT: { ...COMMON_COMPONENT_TEXT },
  SIGNUP_PAGE: { ...SIGNUP_TEXT },
  TYPE_SELECT_PAGE: { ...SELECT_TEXT },
  SET_PROFILE_PAGE: { ...SET_PROFILE_TEXT },
  SIGNUP_COMPLETE_PAGE: { ...SIGNUP_COMPLETE_TEXT },
  ACCOUNT_PAGE: { ...ACCOUNT_TEXT },
};
